on:
  push:
    branches:
      - master

name: release-please
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      test: ${{steps.secrets.outputs.test}}
    steps:
      - id: secrets
        name: Secrets check
        shell: bash
        run: |
          if [ -z "${{secrets.RELEASE_PLEASE_GITHUB_TOKEN}}" ] || [ -z "${{secrets.RELEASE_PLEASE_NPM_TOKEN}}" ]; then
            echo >&2 "Secrets missing, skipping release.";
            echo "test=false" >> $GITHUB_OUTPUT;
          else
            echo "test=true" >> $GITHUB_OUTPUT;
          fi

  release-please:
    needs: check
    if: needs.check.outputs.test == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:

      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{secrets.RELEASE_PLEASE_GITHUB_TOKEN}}
          command: manifest

      - if: ${{steps.release.outputs.releases_created}}
        uses: actions/checkout@v4

      - if: ${{steps.release.outputs.releases_created}}
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: lts/iron
          registry-url: "https://registry.npmjs.org"

      - if: ${{steps.release.outputs.releases_created}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.RELEASE_PLEASE_NPM_TOKEN}}
        run: |
          npm ci
          npm run build
          npm publish --provenance --access public
